<?php
namespace ResourceCatalog\Model;

interface IResourceCatalog extends IResourceCatalogTypeName, IResourceCatalogTypeIdentify, IResourceCatalogTypeEnName, IResourceCatalogTypeDoublePublicity, IResourceCatalogTypeRedBlackList, IResourceCatalogIsConfirm
{

    const TYPE = array(
        'NULL' => 0,
        'XBXZCFXX' => 1,
        'XBXZXKXX' => 2,
        'XZCFXX' => 3,
        'XZXKXX' => 4,
        'SHOUXHBXX' => 5,
        'SHIXHBXX' => 6,
        'JGJCDXZJL' => 7,
        'YXQNZYZ'=> 8,
        'HRBXX' => 9,
        'JKQYPJAJYSMD' => 10,
        'QXTCHJBHJDXX' => 11,
        'XSPJXX' => 12,
        'JYZCXXX' => 13,
        'YSCRJZJJJZGRDXX' => 14,
        'ZFCGDLJGXX' => 15,
        'SJQYJSZXRDXX' => 16,
        'QYRYXX' => 17,
        'SFJDJGCYRYZGXX' => 18,
        'ZYJNZSXX' => 19,
        'ZLJCQYXX' => 20,
        'PGJGXX' => 21,
        'SLGCZBXX' => 22,
        'QYYH' => 23,
        'QSLHXJJTJL' => 24,
        'SLYSXKZXX' => 25,
        'LYQXPDXX' => 26,
        'SPFYSXK' => 27,
        'CPTGLSZXCPRZMD' => 28,
        'ESCJDPGJGHZZS' => 29,
        'SHZZNJXX' => 30,
        'GJJLTQYRZXX' => 31,
        'YXZZDWJBGXX' => 32,
        'CHZZDWXX' => 33,
        'HSZYZGZXX' => 34,
        'QYGSZXXX' => 35,
        'QYSWXZCFXX' => 36,
        'AJNSRXX' => 37,
        'WXHXPQYBHGLQD' => 38,
        'EYQFDGRXX' => 39,
        'WFWGTPXX' => 40,
        'YHYJRJGCFXX' => 41,
        'LSTDFWBA' => 42,
        'EYQFGRXX' => 43,
        'XZXKQYXX' => 44,
        'EYQFQYXX' => 45,
        'SYDWFRDJXX' => 46,
        'YCSTYXHDJXX' => 47,
        'DZDAGZZDWGRBZJL' => 48,
        'HBSZLJDW' => 49,
        'DTJXJGRXX' => 50,
        'SXBZXJGXX' => 51,
        'SXBZXRMD' => 52,
        'YLBXXX' => 53,
        'TJDCDXML' => 54,
        'JDCWFXX' => 55,
        'GERENYONGHU' => 56,
        'GTGSHXX' => 57,
        'CMQYSBXX' => 58,
        'YPLSQYXX' => 59,
        'ZYZXX' => 60,
        'XJFDPDXX' => 61,
        'DYZGXX' => 62,
        'LXSDJXX' => 63,
        'DWAQSCHMDXX' => 64,
        'YZTQSBXXHMD' => 65,
        'JGRYXX' => 66,
        'SXQYHMD' => 67,
        'SPYPTSJBJLGR' => 68,
        'SPYPTSJBJLDW' => 69,
        'HBMPCPXX' => 70,
        'JSZGXX' => 71,
        'SJYXXS' => 72,
        'SYBXXX' => 73,
        'SJJXMXX' => 74,
        'JYJGXINXI' => 75,
        'GRRYXXJYJ' => 76,
        'GRRYXXJTJ' => 77,
        'GRRYXXLFW' => 78,
        'GRRYXXGDJ' => 79,
        'GRRYXXMZJ' => 80,
        'GRRYXXAJJ' => 81,
        'QYYCMLXX' => 82,
        'SBQYXX' => 83,
        'SFJDJGDJXX' => 84,
        'GZJGJBXX' => 85,
        'GZYXX' => 86,
        'JCFLFWSXX' => 87,
        'JCFLFWGZZJBXX' =>88,
        'LSSWSXX' => 89,
        'LSZYZGZXX' => 90,
        'QFGRYHXX' => 91,
        'QFQYYHXX' => 92,
        'FDCKFQYZZXX' => 93,
        'TRQYHJBXX' => 94,
        'QIYEJBXX' => 95,
        'GZRYXX' =>96,
        'SBYHJBXX' => 97,
        'YSZYZCHBGZC' => 98,
        'YSZYZGZXX' => 99,
        'WSHJHSYWYHJCXX' => 100,
        'YLHJSFWJGXX' => 101,
        'JBYFKZJGXX' => 102,
        'FYCRYJLXX' => 103,
        'WSZYJSZGKSWJXX' => 104,
        'QSWCXXXJDWBZ' => 105,
        'YZTQNMGGZHMD' => 106,
        'JGRYXXSWGXJ' => 107,
        'JGRYXXSAJGJ' => 108,
        'JGRYXXSJYJ' => 109,
        'JGRYXXSFGJ' => 110,
        'JGRYXXSSFJ' => 111,
        'MBFQYML' => 112,
        'SHTTDJXX' => 113,
        'QYZXXX' => 114,
        'QYDXXX' => 115,
        'CCJCJGXX' => 116,
        'JGRYXXSLFW' => 117,
        'ZDSSWFAJXX' => 118,
        'GGXYZHPJ' => 119,
        'TEST' => 500
    );

    const USERGROUP_TYPE_RELATIONSHIP = array(
        IUserGroup::ID['NULL'] => array(
            self::TYPE['NULL'],
            self::TYPE['XBXZCFXX'],
            self::TYPE['XBXZXKXX'],
            self::TYPE['SHOUXHBXX'],
            self::TYPE['SHIXHBXX'],
            self::TYPE['TEST']
        ),
        IUserGroup::ID['SFZHGGWYH'] => array(self::TYPE['JGJCDXZJL'], self::TYPE['TEST'], self::TYPE['SJJXMXX'], self::TYPE['GGXYZHPJ']),
        IUserGroup::ID['GQTYCSW'] => array(self::TYPE['YXQNZYZ']),
        IUserGroup::ID['SWMB'] => array(self::TYPE['HRBXX'], self::TYPE['ZYZXX']),
        IUserGroup::ID['RMYHYCSZXZH'] => array(self::TYPE['JKQYPJAJYSMD']),
        IUserGroup::ID['SQXJ'] => array(self::TYPE['QXTCHJBHJDXX']),
        IUserGroup::ID['SZJRMFY'] => array(self::TYPE['XSPJXX'], self::TYPE['SXBZXJGXX'], self::TYPE['SXBZXRMD']),
        IUserGroup::ID['SLSJ'] => array(self::TYPE['JYZCXXX']),
        IUserGroup::ID['SGAJ'] => array(self::TYPE['YSCRJZJJJZGRDXX'], self::TYPE['JDCWFXX']),
        IUserGroup::ID['SCZJ'] => array(self::TYPE['ZFCGDLJGXX']),
        IUserGroup::ID['SGYHXXHWYH'] => array(self::TYPE['SJQYJSZXRDXX']),
        IUserGroup::ID['SGYZCJDGLWYH'] => array(self::TYPE['QYRYXX']),
        IUserGroup::ID['SJYJ'] => array(
            self::TYPE['JSZGXX'],
            self::TYPE['SJYXXS'],
            self::TYPE['JYJGXINXI'],
            self::TYPE['GRRYXXJYJ'],
            self::TYPE['JGRYXXSJYJ']
        ),
        IUserGroup::ID['SSFJ'] => array(
            self::TYPE['SFJDJGCYRYZGXX'],
            self::TYPE['SFJDJGDJXX'],
            self::TYPE['GZJGJBXX'],
            self::TYPE['GZYXX'],
            self::TYPE['JCFLFWSXX'],
            self::TYPE['JCFLFWGZZJBXX'],
            self::TYPE['LSSWSXX'],
            self::TYPE['LSZYZGZXX'],
            self::TYPE['JGRYXXSSFJ']
        ),
        IUserGroup::ID['SRLZYHSHBZJ'] => array(
            self::TYPE['ZYJNZSXX'],
            self::TYPE['YLBXXX'],
            self::TYPE['YZTQSBXXHMD'],
            self::TYPE['SYBXXX'],
            self::TYPE['SBQYXX'],
            self::TYPE['GZRYXX'],
            self::TYPE['YZTQNMGGZHMD']
        ),
        IUserGroup::ID['SJSJ'] => array(self::TYPE['ZLJCQYXX']),
        IUserGroup::ID['SGHJ'] => array(self::TYPE['PGJGXX']),
        IUserGroup::ID['SRQYXGS'] => array(
            self::TYPE['GERENYONGHU'],
            self::TYPE['TRQYHJBXX']
        ),
        IUserGroup::ID['SSLJ'] => array(self::TYPE['SLGCZBXX']),
        IUserGroup::ID['SGDGS'] => array(
            self::TYPE['QYYH'],
            self::TYPE['QFGRYHXX'],
            self::TYPE['QFQYYHXX']
        ),
        IUserGroup::ID['SLYJ'] => array(self::TYPE['QSLHXJJTJL']),
        IUserGroup::ID['SJTYSJ'] => array(self::TYPE['SLYSXKZXX'], self::TYPE['GRRYXXJTJ']),
        IUserGroup::ID['SLYFZWYH'] => array(
            self::TYPE['LYQXPDXX'],
            self::TYPE['XJFDPDXX'],
            self::TYPE['DYZGXX'],
            self::TYPE['LXSDJXX'],
            self::TYPE['GRRYXXLFW'],
            self::TYPE['JGRYXXSLFW'],
        ),
        IUserGroup::ID['SFDCGLJ'] => array(
            self::TYPE['SPFYSXK'],
            self::TYPE['FDCKFQYZZXX'],
            self::TYPE['JGRYXXSFGJ']
        ),
        IUserGroup::ID['SHJBHJ'] => array(self::TYPE['CPTGLSZXCPRZMD']),
        IUserGroup::ID['SSWJ'] => array(self::TYPE['ESCJDPGJGHZZS']),
        IUserGroup::ID['SMZJ'] => array(
            self::TYPE['SHZZNJXX'],
            self::TYPE['GRRYXXMZJ'],
            self::TYPE['MBFQYML'],
            self::TYPE['SHTTDJXX']
        ),
        IUserGroup::ID['SNYJ'] => array(self::TYPE['GJJLTQYRZXX']),
        IUserGroup::ID['SWHGDXWCBS'] => array(
            self::TYPE['YXZZDWJBGXX'],
            self::TYPE['GRRYXXGDJ'],
            self::TYPE['JGRYXXSWGXJ']
        ),
        IUserGroup::ID['SGTZYJ'] => array(self::TYPE['CHZZDWXX']),
        IUserGroup::ID['SWSHJHSYWYH'] => array(
            self::TYPE['HSZYZGZXX'],
            self::TYPE['YSZYZCHBGZC'],
            self::TYPE['YSZYZGZXX'],
            self::TYPE['WSHJHSYWYHJCXX'],
            self::TYPE['YLHJSFWJGXX'],
            self::TYPE['JBYFKZJGXX'],
            self::TYPE['FYCRYJLXX'],
            self::TYPE['WSZYJSZGKSWJXX'],
            self::TYPE['QSWCXXXJDWBZ']
        ),
        IUserGroup::ID['SGJSWJ'] => array(self::TYPE['QYGSZXXX'], self::TYPE['AJNSRXX'], self::TYPE['ZDSSWFAJXX']),
        IUserGroup::ID['SDFSWJ'] => array(self::TYPE['QYSWXZCFXX']),
        IUserGroup::ID['STJJ'] => array(self::TYPE['DTJXJGRXX'], self::TYPE['TJDCDXML']),
        IUserGroup::ID['SSCHZLJGGLJ'] => array(
            self::TYPE['QIYEJBXX'],
            self::TYPE['GTGSHXX'],
            self::TYPE['CMQYSBXX'],
            self::TYPE['YPLSQYXX'],
            self::TYPE['JGRYXX'],
            self::TYPE['SXQYHMD'],
            self::TYPE['SPYPTSJBJLGR'],
            self::TYPE['SPYPTSJBJLDW'],
            self::TYPE['HBMPCPXX'],
            self::TYPE['QYYCMLXX'],
            self::TYPE['QYZXXX'],
            self::TYPE['QYDXXX'],
            self::TYPE['CCJCJGXX']
        ),
        IUserGroup::ID['SAQSCJDGLJ'] => array(
            self::TYPE['WXHXPQYBHGLQD'],
            self::TYPE['DWAQSCHMDXX'],
            self::TYPE['GRRYXXAJJ'],
            self::TYPE['JGRYXXSAJGJ']
        ),
        IUserGroup::ID['ZGYDYCFGS'] => array(self::TYPE['EYQFDGRXX']),
        IUserGroup::ID['YCHCZYCBZ'] => array(self::TYPE['WFWGTPXX']),
        IUserGroup::ID['SYJFJ'] => array(self::TYPE['YHYJRJGCFXX']),
        IUserGroup::ID['SGGZWGLJ'] => array(self::TYPE['LSTDFWBA']),
        IUserGroup::ID['ZGDXYCFGS'] => array(self::TYPE['EYQFGRXX']),
        IUserGroup::ID['SCSGLXZZFJ'] => array(self::TYPE['XZXKQYXX']),
        IUserGroup::ID['ZGLTYCFGS'] => array(self::TYPE['EYQFQYXX']),
        IUserGroup::ID['SJGBZWYHBGS'] => array(self::TYPE['SYDWFRDJXX']),
        IUserGroup::ID['STYJ'] => array(self::TYPE['YCSTYXHDJXX']),
        IUserGroup::ID['SDAJ'] => array(self::TYPE['DZDAGZZDWGRBZJL']),
        IUserGroup::ID['SKXJSJ'] => array(self::TYPE['HBSZLJDW']),
        IUserGroup::ID['SWGS'] => array(self::TYPE['SBYHJBXX'])
    );

    const STATUS_NORMAL = 0;

    const STATUS_DELETE = -2;
}
